
[package]
name = "stable-chess-script"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { workspace = true }
serde_json = "1.0"
hex = "0.4"

[build-dependencies]
sp1-helper = { workspace = true }
